### ISSUE TITLE
Users created without ability to leverage saml authentication.

### ISSUE THREAD

**Issue by briand44** [ITS-UofIowa/sitenow_user_create#6]
When a webmaster creates a new user account the account is created but the checkbox "Enable this user to leverage SAML authentication" is not checked. Without that checkbox being checked, I don't believe those users can authenticate.

**Comment by briand44** [comment]
This may not be an issue because we have "Automatically enable SAML authentication for existing users upon successful login" set in the saml configuration.

**Comment by genjohnson** [comment]
This is not an issue because of the SAML config. I had Cody help me test this out. I created a user account for him and un-checked the box for "Enable this user to leverage SAML authentication". He was able to login, and after he logged in noticed that the box was checked.
